# Create a persistent volume claim (PVC) that exposes the PV to a pod https://kubernetes.io/docs/concepts/storage/persistent-volumes/#persistentvolumeclaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "outlook-integration.fullname" . }}
  labels:
    {{- include "outlook-integration.labels" . | nindent 4 }}
spec:
  storageClassName: {{ .Values.volume.storageClassName }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.volume.capacity }}